# Generated by Django 5.1.1 on 2024-09-29 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "place",
                    models.CharField(
                        help_text="Укажите место выполнения привычки",
                        max_length=60,
                        verbose_name="Место выполнения",
                    ),
                ),
                (
                    "time",
                    models.TimeField(
                        help_text="Укажите время выполнения привычки",
                        verbose_name="Время выполнения",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        help_text="Укажите действие, которое нужно выполнять",
                        max_length=100,
                        verbose_name="Действие",
                    ),
                ),
                (
                    "is_pleasant_habit",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        help_text="Укажите, является ли привычка приятной",
                        null=True,
                        verbose_name="Приятная привычка",
                    ),
                ),
                (
                    "periodicity",
                    models.CharField(
                        choices=[
                            ("1 time in 6 days", "1 раз в 6 дня"),
                            ("1 time in 3 days", "1 раз в 3 дня"),
                            ("1 time in 7 days", "1 раз в неделю"),
                            ("1 time in 2 days", "1 раз в 2 дня"),
                            ("1 time in 5 days", "1 раз в 5 дня"),
                            ("1 time in 4 days", "1 раз в 4 дня"),
                            ("1 time in 1 days", "1 раз в день"),
                        ],
                        help_text="Укажите периодичность выполнения привычки",
                        max_length=30,
                        verbose_name="Периодичность выполнения",
                    ),
                ),
                (
                    "reward",
                    models.CharField(
                        blank=True,
                        help_text="Укажите вознвграждение за выполнение привычки",
                        max_length=100,
                        null=True,
                        verbose_name="Вознаграждение",
                    ),
                ),
                (
                    "time_to_complete",
                    models.PositiveIntegerField(
                        help_text="Укажите время на выполнение привычки",
                        verbose_name="Время на выполнение",
                    ),
                ),
                (
                    "is_publicity",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        help_text="Укажите, является ли привычка публичная",
                        null=True,
                        verbose_name="Публичная привычка",
                    ),
                ),
                (
                    "associated_habit",
                    models.ForeignKey(
                        blank=True,
                        help_text="Укажите связанную привычку",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="habits",
                        to="habits.habit",
                        verbose_name="Связанная привычка",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
            },
        ),
    ]
