# Generated by Django 5.1.1 on 2024-09-30 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="periodicity",
            field=models.CharField(
                choices=[
                    ("1 time in 6 days", "1 раз в 6 дня"),
                    ("1 time in 7 days", "1 раз в неделю"),
                    ("1 time in 1 days", "1 раз в день"),
                    ("1 time in 2 days", "1 раз в 2 дня"),
                    ("1 time in 3 days", "1 раз в 3 дня"),
                    ("1 time in 4 days", "1 раз в 4 дня"),
                    ("1 time in 5 days", "1 раз в 5 дня"),
                ],
                help_text="Укажите периодичность выполнения привычки",
                max_length=30,
                verbose_name="Периодичность выполнения",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
    ]
